export enum ProcessStatus {

  NEW = "NEW",
  WEBFORM_SENT = "WEBFORM_SENT",
  REQUEST_SENT = "REQUEST_SENT",
  RESPONSE_RECEIVED = "RESPONSE_RECEIVED",
  MEETING_SCHEDULED = "MEETING_SCHEDULED",
  WAITING_CONFIRMATION = "WAITING_CONFIRMATION",
  WAITING_DECISION = "WAITING_DECISION",
  REJECTED_OWNER = "REJECTED_OWNER",
  REJECTED_ME = "REJECTED_ME",
  OUTDATED = "OUTDATED",
  DUPLICATE = "DUPLICATE",
  UNKNOWN = "UNKNOWN"

}
